import os
import json
from datetime import datetime

def review_all_pending_messages() -> dict:
    """
    Reviews all pending outreach messages generated by the outreach layer.
    Approves them if they meet quality standards, or edits/rejects them.
    """
    results = {
        "reviewed": 0,
        "approved": 0,
        "needs_edit": 0,
        "rejected": 0
    }
    
    # Check if there's a pending messages file
    pending_file = "results/outreach/pending_messages.json"
    if not os.path.exists(pending_file):
        print("   No pending messages found.")
        return results
        
    try:
        with open(pending_file, "r") as f:
            messages = json.load(f)
    except:
        return results
        
    reviewed_messages = []
    
    for msg in messages:
        results["reviewed"] += 1
        
        # Simple heuristic review for now
        content = msg.get("content", "").lower()
        if len(content) < 20:
            msg["status"] = "rejected"
            msg["review_notes"] = "Message too short."
            results["rejected"] += 1
        elif "placeholder" in content or "[insert" in content:
            msg["status"] = "needs_edit"
            msg["review_notes"] = "Contains unreplaced placeholders."
            results["needs_edit"] += 1
        else:
            msg["status"] = "approved"
            msg["review_notes"] = "Looks good."
            results["approved"] += 1
            
        reviewed_messages.append(msg)
        
    # Save reviewed messages back
    with open(pending_file, "w") as f:
        json.dump(reviewed_messages, f, indent=2)
        
    return results